
/*
 * Licensed Materials - Property of IBM
 *
 * trousers - An open source TCG Software Stack
 *
 * (C) Copyright International Business Machines Corp. 2004
 *
 */

/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <string.h>

#include <gtk/gtk.h>

#include "tss/tss.h"

#include "interface.h"
#include "support.h"

#undef ENABLE_NLS

/*
 * DisplayPINWindow()
 *
 * Popup the dialog to collect an existing password.
 *
 * string - buffer that the password will be passed back to caller in
 * w_popup - UNICODE string to be displayed in the title bar of the dialog box
 *
 */
TSS_RESULT DisplayPINWindow(char *string, UNICODE *w_popup)
{
  GtkWidget *dialog1;
  struct userdata ud;
  char c_title[256];
  mbstate_t ps;

  memset(&ps, 0, sizeof(mbstate_t));

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  wcsrtombs(c_title, (const wchar_t **)&w_popup, 256, &ps);

  ud.string = string;

  gtk_set_locale();
  gtk_init_check((int *)NULL, (char ***)NULL);

  dialog1 = create_password_dialog(&ud, c_title);
  gtk_widget_show(dialog1);

  gtk_main();

  return TSS_SUCCESS;
}

/*
 * DisplayNewPINWindow()
 *
 * Popup the dialog to collect a new password.
 *
 * string - buffer that the password will be passed back to caller in
 * w_popup - UNICODE string to be displayed in the title bar of the dialog box
 *
 */
TSS_RESULT DisplayNewPINWindow(char *string, UNICODE *w_popup)
{
  GtkWidget *dialog1;
  struct userdata ud;
  char c_title[256];
  mbstate_t ps;

  memset(&ps, 0, sizeof(mbstate_t));

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  wcsrtombs(c_title, (const wchar_t **)&w_popup, 256, &ps);

  ud.string = string;

  gtk_set_locale();
  gtk_init_check((int *)NULL, (char ***)NULL);

  dialog1 = create_new_password_dialog(&ud, c_title);
  gtk_widget_show(dialog1);

  gtk_main();

  return TSS_SUCCESS;
}

